# Generated by Django 4.1.5 on 2023-11-25 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
