# Generated by Django 4.1.4 on 2022-12-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_userexpenses_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExpenses',
            new_name='UserExpense',
        ),
    ]
