# Generated by Django 4.1.4 on 2022-12-14 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_rename_userexpenses_userexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpense',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
