# Generated by Django 4.1.4 on 2022-12-15 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_userexpense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbudget',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='user',
        ),
        migrations.AddField(
            model_name='userexpense',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
