# Generated by Django 4.1.4 on 2022-12-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_rename_user_userbudget_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbudget',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userexpense',
            old_name='user_id',
            new_name='user',
        ),
    ]
